import React from "react";
import styled from "styled-components";
function LoadingAnimation() {
    return (
        <LoadingAnimationStyled>
            <div class="loadingio-spinner-ellipsis-nhx1yx8452g">
                {" "}
                <div class="ldio-2mgiz4odyj1">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </LoadingAnimationStyled>
    );
}

const LoadingAnimationStyled = styled.div`
 
@keyframes ldio-2mgiz4odyj1 {
   0% { transform: translate(11.82px,78.8px) scale(0); }
  25% { transform: translate(11.82px,78.8px) scale(0); }
  50% { transform: translate(11.82px,78.8px) scale(1); }
  75% { transform: translate(78.8px,78.8px) scale(1); }
 100% { transform: translate(145.78px,78.8px) scale(1); }
}
@keyframes ldio-2mgiz4odyj1-r {
   0% { transform: translate(145.78px,78.8px) scale(1) }
 100% { transform: translate(145.78px,78.8px) scale(0); }
}
@keyframes ldio-2mgiz4odyj1-c {
   0% { background: #e75d5d }
  25% { background: #f9ae5c }
  50% { background: #ffffff }
  75% { background: #28292f }
 100% { background: #e75d5d }
}
.ldio-2mgiz4odyj1 div {
  position: absolute;
  width: 39.4px;
  height: 39.4px;
  border-radius: 50%;
  transform: translate(78.8px,78.8px) scale(1);
  background: #e75d5d;
  animation: ldio-2mgiz4odyj1 1s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-2mgiz4odyj1 div:nth-child(1) {
  background: #28292f;
  transform: translate(145.78px,78.8px) scale(1);
  animation: ldio-2mgiz4odyj1-r 0.25s infinite cubic-bezier(0,0.5,0.5,1), ldio-2mgiz4odyj1-c 1s infinite step-start;
}.ldio-2mgiz4odyj1 div:nth-child(2) {
  animation-delay: -0.25s;
  background: #e75d5d;
}.ldio-2mgiz4odyj1 div:nth-child(3) {
  animation-delay: -0.5s;
  background: #28292f;
}.ldio-2mgiz4odyj1 div:nth-child(4) {
  animation-delay: -0.75s;
  background: #ffffff;
}.ldio-2mgiz4odyj1 div:nth-child(5) {
  animation-delay: -1s;
  background: #f9ae5c;
}
.loadingio-spinner-ellipsis-nhx1yx8452g {
    width: 197px;
    height: 197px;
    position: relative;
    left: 18rem;
    display: inline-block;
    margin: auto;
    overflow: hidden;
}
.ldio-2mgiz4odyj1 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
      background-color: rgb(228,230,235);
  transform-origin: 0 0; /* see note above */
}
.ldio-2mgiz4odyj1 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
`;

export default LoadingAnimation;
